---
- name: Create GitLab groups
  when: gitlab_groups | length > 0
  block:
    - name: Template Rails runner script
      ansible.builtin.template:
        src: create_groups.rb.j2
        dest: /tmp/create_groups.rb
        mode: '0644'

    - name: Execute Rails runner to create groups
      ansible.builtin.shell: gitlab-rails runner /tmp/create_groups.rb
      register: rails_output
      changed_when: "'created' in rails_output.stdout"

    - name: Remove Rails runner script
      ansible.builtin.file:
        path: /tmp/create_groups.rb
        state: absent
